Watcha op543 use constant insted of config for synapse informations
watcha-fr/watcha_integrator pull request #2
Opened 2020-11-12 10:55 UTC by KevICO

Resolution of OP task : https://op.watcha.fr/projects/watcha/work_packages/543/activity?query_id=43

2020-11-12 10:56 UTC, KevICO commented on lib/Extension/Synapse.php
> +class Synapse
Je ne suis pas convaincu par ce nom de classe.
En effet la constante SERVICE_ACCOUNT_NAME ne concerne pas uniquement Synapse On parle vraiement du compte de service Watcha qui peut être amené à réaliser des opérations en dehors de faire communiquer Synapse et Nextcloud.
Du coup je n'ai rien trouvé de mieux, mais je pense qu'il y a mieux comme nom

2020-11-26 21:16 UTC, c-cal requested changes

2020-11-26 21:16 UTC, c-cal commented on lib/Extension/Synapse.php
> +class Synapse
Changer le nom de la classe impliquerait aussi de changer le nom de LOGIN_ENDPOINT et NOTIFICATION_ENDPOINT propre à Synapse... peut être les préfixer par SYNAPSE_ et renommer la classe (et le fichier) WatchaIntegrator, non ?

2020-11-26 21:16 UTC, c-cal commented on lib/FilesHooks.php
> +        $this->serviceAccountPassword = $this->config->getSystemValue('synapse_account_password') ?: $this->config->getSystemValue('service_account_password');
```suggestion
        $this->serviceAccountPassword = $this->config->getSystemValue('synapse_account_password', $this->config->getSystemValue('service_account_password'));
```

2020-11-26 21:16 UTC, c-cal commented on lib/FilesHooks.php
> +        $synapseUserId = "@" . $this->serviceAccountName . ":" . $hostname;
```suggestion
        $synapseUserId = "@{$this->serviceAccountName}:$hostname";
```

2020-11-26 21:16 UTC, c-cal commented on lib/FilesHooks.php
> +            $this->logger->info("Request success to " . $homeserverUrl . Synapse::LOGIN_ENDPOINT);
```suggestion
            $this->logger->info("Request success to $homeserverUrl" . Synapse::LOGIN_ENDPOINT);
```

2020-11-27 14:03 UTC, KevICO commented on lib/Controller/WatchaShareAPIController.php
> +        $this->$serviceAccountName = $this->config->getSystemValue("nextcloud_account_name") ?: Synapse::SERVICE_ACCOUNT_NAME;
Ta proposition est juste et c'est une modification que j'ai intégrée dans la PR https://github.com/watcha-fr/watcha_integrator/pull/3
Cette fonction va récupérer la valeur de la clé "nextcloud_account_name" du fichier de config.
Si elle n'existe pas, elle va récupérer la valeur de la constante SERVICE_ACCOUNT_NAME de la classe Synapse.

2020-11-27 14:05 UTC, KevICO commented on lib/Extension/Synapse.php
> + * @copyright Copyright (c) 2016, ownCloud, Inc.
C'est un copier coller bête et méchant :D

2020-11-27 14:07 UTC, KevICO commented on lib/FilesHooks.php
> +        $this->serviceAccountPassword = $this->config->getSystemValue('synapse_account_password') ?: $this->config->getSystemValue('service_account_password');
Tu utilise quoi comme formatter pour php?

2020-11-27 14:14 UTC, KevICO commented on lib/Extension/Synapse.php
> +class Synapse
Je ne suis pas plus convaincu par le nom WatchaIntegrator comme nom de fichier sachant que c'est le nom porté par l'app. 
Pour le moment je laisse comme ça et si une meilleure idée nous vient on changera à ce moment là ;)

2020-11-27 16:09 UTC, c-cal approved these changes

2020-11-30 08:23 UTC, merged

2020-12-11 10:42 UTC, c-cal commented on lib/FilesHooks.php
> +        $this->serviceAccountPassword = $this->config->getSystemValue('synapse_account_password') ?: $this->config->getSystemValue('service_account_password');
Intelephense ds vscode