Watcha op571 purify nextcloud ui
watcha-fr/watcha_integrator pull request #4
Opened 2020-11-24 14:52 UTC by KevICO

Resolution of OP task n°571 : https://op.watcha.fr/projects/watcha/work_packages/571/activity?query_id=43

Work with :

2020-11-27 16:33 UTC, c-cal requested changes
hideWatchaGroupsScript.js needs to be refactored

2020-11-27 16:33 UTC, c-cal commented on js/hideWatchaGroupsScript.js
> +            if (groupName.startsWith(watchaGroupPattern)) {
```suggestion
            if (groupName.startsWith(watchaGroupPrefix)) {
```

2020-11-27 16:33 UTC, c-cal commented on js/hideWatchaGroupsScript.js
> +                    if (addedNode.innerText.includes(watchaGroupPattern)) {
```suggestion
                    if (addedNode.innerText.includes(watchaGroupPrefix)) {
```

2020-11-27 16:33 UTC, c-cal commented on js/hideWatchaGroupsScript.js
> +                            sharingEntry.innerText.includes(watchaGroupPattern)
```suggestion
                            sharingEntry.innerText.includes(watchaGroupPrefix)
```

2020-11-27 16:33 UTC, c-cal commented on js/hideWatchaGroupsScript.js
> +                        if (tag.innerText.includes(watchaGroupPattern)) {
```suggestion
                        if (tag.innerText.includes(watchaGroupPrefix)) {
```

2020-11-27 16:33 UTC, c-cal commented on js/hideWatchaGroupsScript.js
> +                        if (group.includes(watchaGroupPattern)) {
```suggestion
                        if (group.includes(watchaGroupPrefix)) {
```

2020-11-27 16:33 UTC, c-cal commented on js/hideWatchaGroupsScript.js
> +        if (groupName.includes(watchaGroupPattern)) {
```suggestion
        if (groupName.includes(watchaGroupPrefix)) {
```

2020-11-30 10:37 UTC, KevICO commented
> hideWatchaGroupsScript.js needs to be refactored

J'ai ajouté quelques fonction pour décomposer le code et modifier des noms de variables pour faciliter la compréhension.
Je te laisse review le résultat.

2020-12-07 18:03 UTC, c-cal requested changes

2020-12-21 13:19 UTC, closed without merging